export const EDIT_COMPANY = 'EDIT_COMPANY';
export const EDIT_ACCOUNTING = 'EDIT_ACCOUNTING';
export const ADD_SHAREHOLDER = 'ADD_SHAREHOLDER';
export const EDIT_SHAREHOLDER = 'EDIT_SHAREHOLDER';
export const RESET_CONTEXT = 'RESET_CONTEXT';
export const REGISTER = 'REGISTER';
